### PR TITLE
Cleanup + test fixes

### PR DESCRIPTION
**Pull request by camirmas**
### Changes

- Fixes the test suite
- Fixes the documentation build
- Removes redundant and unused `resource_files`
- Upgrades to PySAM 4.1.0 (possibly 4.2.0)

### Followup Items

_see commit messages for more info_

- Currently we can't use the most recent version of `shapely`, as its API has changed, causing test errors
- A number of tests in `tests/analysis` appear to be outdated and can possibly be removed as we work on assessing the code in the `to_organize` directory. I met with @kbrunik to discuss this and we'll be following up soon, but we should be fine to not run these for the time being

My thought is to get this in so that we're back to a stable baseline, and make followup issues for the Project Board.

### CODE REVIEW

**Comment by camirmas** [comment]
@jaredthomas68 This [run](https://github.com/camirmas/HOPP/actions/runs/5859784714/job/15886503339) shows the current state of the tests, with all tests in `tests/hopp` passing, but with `test_pressure_vessel` disabled. I'm not quite sure how to handle the tests in `tests/analysis`, as there are some missing files as well as numerical differences that I'm unfamiliar with.

**Comment by camirmas** [comment]
Tests passing on my [fork](https://github.com/camirmas/HOPP/actions/runs/5861322080/job/15891167940)

**Review by jaredthomas68 — APPROVED** [review]

**Comment by camirmas** [comment]
Most recent build [here](https://github.com/camirmas/HOPP/actions/runs/5885382067/job/15961727038), `test_pressure_vessel` is re-enabled and now PySAM is up to date, only 4 failing tests remaining

**Comment by camirmas** [comment]
Tests finally passing! https://github.com/camirmas/HOPP/actions/runs/5930176279/job/16079337183

**Pull request merged**
