### PR TITLE
Run simple PV model PVWattsv8 with a custom detailed layout

### PR DESCRIPTION
**Pull request by Matthew-Boyd**
@dguittet Could you please take a look and ensure this is what Engie needs?

### CODE REVIEW

**Review by dguittet — APPROVED** [review]
lgtm

**Comment by dguittet** [comment]
@Matthew-Boyd Do you also get this error? 

```
    def __init__(self,
                 site: SiteInfo,
                 pv_config: dict):
        """
    
        :param pv_config: dict, with keys ('system_capacity_kw', 'layout_params')
            where 'layout_params' is of the SolarGridParameters type
        """
        if 'system_capacity_kw' not in pv_config.keys():
>           raise ValueError
E           ValueError

hybrid/pv_source.py:26: ValueError
```

**Comment by Matthew-Boyd** [comment]
> @Matthew-Boyd Do you also get this error?
> 
> ```
>     def __init__(self,
>                  site: SiteInfo,
>                  pv_config: dict):
>         """
>     
>         :param pv_config: dict, with keys ('system_capacity_kw', 'layout_params')
>             where 'layout_params' is of the SolarGridParameters type
>         """
>         if 'system_capacity_kw' not in pv_config.keys():
> >           raise ValueError
> E           ValueError
> 
> hybrid/pv_source.py:26: ValueError
> ```

Now I do. I'm not sure what happened, but I think a lot of the new changes were lost with one of the merges. I'm currently working on it.

**Comment by Matthew-Boyd** [comment]
@dguittet Do you have any insight as to why this sklearn dependency failure is happening again? Your updates to the requirements are here already.

**Comment by dguittet** [comment]
It may have to do with there being no way to enforce the order of the pip install requirements. I will simply remove scikit-optimize from the requirements list

**Pull request merged**
